In [3]:
import numpy as np

In [93]:
n = 100
k = 3
np.set_printoptions(precision=3)

1)

In [94]:
X = np.random.normal(0, 1, (n, k))

In [95]:
np.dot(X.transpose(), X)

array([[ 96.947,  27.802,  -6.43 ],
       [ 27.802, 110.156,  -4.317],
       [ -6.43 ,  -4.317,  92.799]])

2)

In [96]:
def matrix_sum(X, Y):
    s = np.zeros((len(X), len(X[1])))
    for i in range(len(X)): 
        for j in range(len(X[0])): 
            s[i][j] = X[i][j] + Y[i][j]
    return s

In [97]:
t = np.zeros((k, k))
for i in range(n):
    t = matrix_sum(t, np.dot(np.array([X[i]]).transpose(), np.array([X[i]])))

In [98]:
t

array([[ 96.947,  27.802,  -6.43 ],
       [ 27.802, 110.156,  -4.317],
       [ -6.43 ,  -4.317,  92.799]])

t coincides with $X^TX$

3)

In [99]:
np.cov(X.transpose())

array([[ 0.964,  0.29 , -0.059],
       [ 0.29 ,  1.107, -0.047],
       [-0.059, -0.047,  0.935]])

In [100]:
np.mean(X, axis=0)

array([ 0.123, -0.073, -0.051])

Populational mean and covariance matrix are:
$$\mu = \begin{pmatrix}
0\\0\\0\end{pmatrix}, \Sigma = \begin{pmatrix}
1 & 0 & 0\\0&1&0\\0&0&1\end{pmatrix}$$ as we can see the sample mean and covariance matrix substantially differ from the populational

4)

It is known that $rg(X^TX) = rg(X)$ which is equal to 3 unless the columns of the matrix $X$ are linearly dependent.
Since $x \sim N(0, I)$ then $\mathbb{E}[xx^T] = I$ whihch means that $rg \mathbb{E}[xx^T] = 3$.
$rg[x_ix_i^T] = rg[x_i] = 1$.

In [101]:
n*np.linalg.inv(np.dot(X.transpose(), X))

array([[ 1.116, -0.279,  0.064],
       [-0.279,  0.979,  0.026],
       [ 0.064,  0.026,  1.083]])

$\mathbb{E}[xx^T]^-1 = I$

5)

In [106]:
w = np.random.randint(1, 10, size=100)
omega = np.diag(w)

$X^T\Omega X$:

In [108]:
np.dot(np.dot(X.transpose(), omega), X)

array([[481.146, 128.201, -23.792],
       [128.201, 526.26 , -61.937],
       [-23.792, -61.937, 501.043]])

$\sum_{i=1}^{n} \omega_i x_i x_i^T$:

In [109]:
t = np.zeros((k, k))
for i in range(n):
    t = matrix_sum(t, w[i]*np.dot(np.array([X[i]]).transpose(), np.array([X[i]])))
t

array([[481.146, 128.201, -23.792],
       [128.201, 526.26 , -61.937],
       [-23.792, -61.937, 501.043]])